<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '36c649214535e04a4ad0c449e02b0586',
  'DATABASE_URL' => 'mysql://root:secret@database:3306/symfony_docker?serverVersion=8&charset=utf8mb4',
  'PT_DATABASE_URL' => 'postgresql://docker:docker123@185.98.62.150:5433/pati-dev?serverVersion=15&charset=utf8',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'SERVER_HOST' => 'localhost',
  'SERVER_SCHEME' => 'http',
  'SERVER_PORT' => '8080',
  'host' => '185.98.62.150',
  'port' => '5433',
  'dbname' => 'pati-dev',
  'user' => 'docker',
  'password' => 'docker123',
);
