<?php

<<<<<<< HEAD
// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
=======
// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
>>>>>>> origin/master
  'APP_SECRET' => '36c649214535e04a4ad0c449e02b0586',
  'DATABASE_URL' => 'mysql://root:secret@database:3306/symfony_docker?serverVersion=8&charset=utf8mb4',
  'CUSTOM_DATABASE_URL' => 'mysql://root:secret@database:3306/symfony_docker?serverVersion=8&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'SERVER_HOST' => 'localhost',
  'SERVER_SCHEME' => 'http',
  'SERVER_PORT' => '8080',
);
