<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '36c649214535e04a4ad0c449e02b0586',
  'DATABASE_URL' => 'postgresql://postgres:12345@10.0.2.12:5432/pati?serverVersion=9.3&charset=utf8',
  'PT_DATABASE_URL' => 'postgresql://postgres:12345@10.0.2.12:5432/pati?serverVersion=9.3&charset=utf8',
  'PT_ARASTIR_GOZLE' => 'postgresql://postgres:12345@10.0.2.12:5432/arastirgozle?serverVersion=9.3&charset=utf8',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://itirazbildirim@ankarapatent.com:STARTTLS@smtp.office365.com:587',
  'SERVER_HOST' => 'localhost',
  'SERVER_SCHEME' => 'http',
  'SERVER_PORT' => '8080',
  'host' => '185.98.62.150',
  'port' => '5433',
  'dbname' => 'pati-dev',
  'user' => 'docker',
  'password' => 'docker123',
);
